development:
  adapter: postgresql
  database: ocd_development
  host: localhost

test:
  adapter: postgresql
  database: ocd_test
  host: localhost

production:
  adapter: postgresql
  database: ocd_production
  host: localhost
